# Reference
alignment:
    fasta: /projects/HostSeq/align_fasta_ref/Genome_England/GRCh38_full_analysis_set_plus_decoy_hla.fa
    fasta_g1k_v37_487: /projects/bioSCRATCH/resources/human_g1k_v37_487/human_g1k_v37_487.fasta
    hla_fasta: /projects/vtrinh_prj/mcalingo/hostseq/HLA-VBSeq_test/tools/hla_all_v2.fasta
    
# Software and tools
software:
    samtools1: /gsc/software/linux-x86_64-centos7/samtools-1.9/bin/samtools
    samtools2: /gsc/software/linux-x86_64-centos7/samtools-1.14/bin/samtools
    bwa: /gsc/software/linux-x86_64-centos7/bwa-0.7.6a/bwa
    java1: /gsc/software/linux-x86_64-centos7/jdk1.8.0_172/bin/java
    java2: /gsc/software/linux-x86_64-centos7/jdk-15.0.1/bin/java
    seqtk: /gsc/software/linux-x86_64-centos7/seqtk-1.3/seqtk
    hlavbseq: /projects/vtrinh_prj/mcalingo/hostseq/HLA-VBSeq_test/tools/HLAVBSeq.jar
    picard: /gsc/software/linux-x86_64-centos7/picard-2.4.2/picard.jar
    parse_result: /projects/vtrinh_prj/mcalingo/hostseq/HLA-VBSeq_test/tools/parse_result.pl
    gen_report: /projects/vtrinh_prj/mcalingo/hostseq/HLA-VBSeq_test/tools/call_hla_digits.py
    python: /home/mcalingo/py2venv/bin/python

# Tools specifics
samtools:
    threads: 8
    mem: 8000 #MB
    time_limit: 7200 #mins
picard:
    mem: 16000 #MB
bwa:
    threads: 8
    mem: 16000 #MB
    time_limit: 7200 #mins
seqtk:
    threads: 8
    mem: 2048 #MB
    time_limit: 7200 #mins

# Useful directories    
tmp_dir: /projects/HostSeq/scratch/hostseq
outs_dir: /projects/HostSeq/hostseq_smk_hla
allele_list: /projects/vtrinh_prj/mcalingo/hostseq/HLA-VBSeq_test/tools/Allelelist_v2.txt

# Samples input
samples: configs/samples.csv
string_replacement:
    remove_substring: _LME_R{1-2}_001
